//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolFaceRecognition.SharedLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolFaceRecognition.SharedLibrary.ConstantLiterals", typeof(ConstantLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat tapılmadı..
        /// </summary>
        public static string DataNotFoundMessage {
            get {
                return ResourceManager.GetString("DataNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ata adı boş ola bilməz..
        /// </summary>
        public static string FatherNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("FatherNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qrup təyin edilməlidir..
        /// </summary>
        public static string GroupCanNotBeEmpty {
            get {
                return ResourceManager.GetString("GroupCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat daxil edilməyib..
        /// </summary>
        public static string InputValuesIsEmpty {
            get {
                return ResourceManager.GetString("InputValuesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad boş ola bilməz..
        /// </summary>
        public static string NameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("NameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad boş ola bilməz..
        /// </summary>
        public static string SurnameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SurnameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər boş ola bilməz..
        /// </summary>
        public static string UserCityCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserCityCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email boş ola bilməz..
        /// </summary>
        public static string UserEmailCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserEmailCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email düzgün formatda deyil..
        /// </summary>
        public static string UserEmailIsNotCorrect {
            get {
                return ResourceManager.GetString("UserEmailIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin bu əməliyyatı etmək üçün icazəniz yoxdur.
        /// </summary>
        public static string UserForbiddenMessage {
            get {
                return ResourceManager.GetString("UserForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxili xəta baş verdi..
        /// </summary>
        public static string UserInternalErrorMessage {
            get {
                return ResourceManager.GetString("UserInternalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcazəniz yoxdur..
        /// </summary>
        public static string UserIsNotAuthorizedMessage {
            get {
                return ResourceManager.GetString("UserIsNotAuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi adı boş ola bilməz..
        /// </summary>
        public static string UserNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsdifadəçi adı və ya parol səhvdir..
        /// </summary>
        public static string UserNameOrPasswordIsFalse {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi tapılmadı..
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parol boş ola bilməz..
        /// </summary>
        public static string UserPasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserPasswordCanNotBeEmpty", resourceCulture);
            }
        }
    }
}
