// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolFaceRecognition.DAL.AppDbContext;

#nullable disable

namespace SchoolFaceRecognition.DAL.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20221206035201_RolePermissionsWasAdded")]
    partial class RolePermissionsWasAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Audience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.ToTable("AUDIENCES", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("CLIENTS", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.ClientAudience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AudienceId")
                        .HasColumnType("int")
                        .HasColumnName("AUDIENCE_ID");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_ID");

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("AudienceId", "ClientId")
                        .IsUnique();

                    b.ToTable("CLIENTSAUDIENCES", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.ToTable("PERMISSIONS", "AUTH");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 94, DateTimeKind.Local).AddTicks(8577),
                            IsDeleted = false,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 2,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 94, DateTimeKind.Local).AddTicks(8593),
                            IsDeleted = false,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 3,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 94, DateTimeKind.Local).AddTicks(8594),
                            IsDeleted = false,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 94, DateTimeKind.Local).AddTicks(8596),
                            IsDeleted = false,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPIRATION");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TOKEN");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("REFRESH_TOKEN", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.ToTable("ROLES", "AUTH");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 142, DateTimeKind.Local).AddTicks(7734),
                            IsDeleted = false,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 2,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 142, DateTimeKind.Local).AddTicks(7751),
                            IsDeleted = false,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 3,
                            CreaterUser = "Admin",
                            CreationDate = new DateTime(2022, 12, 6, 7, 52, 1, 142, DateTimeKind.Local).AddTicks(7753),
                            IsDeleted = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.Property<int>("UserRolePermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PERMISSION_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserRolePermissionId");

                    b.HasIndex("RoleTypeId", "UserRolePermissionId")
                        .IsUnique();

                    b.ToTable("ROLES_PERMISSIONS", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("AGE");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_BLOCKED");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_USERS_EMAIL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UK_USERS_USER_NAME");

                    b.ToTable("USERS", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("USERS_ROLES", "AUTH");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Continuity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Participant")
                        .HasColumnName("ACTIVITY");

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DATE");

                    b.Property<int?>("StudentId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CONTINUITIES", "SCHOOL");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<int?>("SpecialityId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("SPECIALITY_ID");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_GROUP_NAME");

                    b.HasIndex("SpecialityId");

                    b.ToTable("GROUPS", "SCHOOL");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_SPECIALITY_CODE");

                    b.ToTable("SPECIALITIES", "SCHOOL");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("CreaterUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CREATER_USER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FATHER_NAME");

                    b.Property<int?>("GroupId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("RemoverUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("REMOVER_USER");

                    b.Property<DateTime?>("RemovingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("REMOVING_DATE");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SURNAME");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdaterUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UPDATER_USER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("STUDENTS", "SCHOOL");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.ClientAudience", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.Audience", "Audience")
                        .WithMany("ClientAudiences")
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CLIENTSAUDIENCES_AUDIENCE_ID");

                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.Client", "Client")
                        .WithMany("ClientAudiences")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CLIENTSAUDIENCES_CLIENT_ID");

                    b.Navigation("Audience");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("SchoolFaceRecognition.Core.Entities.Auth.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("UserRolePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFaceRecognition.Core.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Continuity", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Student", "Student")
                        .WithMany("Continuities")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTINUITIES_STUDENT_ID");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Group", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Speciality", "Speciality")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialityId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUPS_SPECIALITY_ID");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Student", b =>
                {
                    b.HasOne("SchoolFaceRecognition.Core.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_STUDENTS_GROUP_ID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Audience", b =>
                {
                    b.Navigation("ClientAudiences");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Client", b =>
                {
                    b.Navigation("ClientAudiences");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Auth.User", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Speciality", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SchoolFaceRecognition.Core.Entities.Student", b =>
                {
                    b.Navigation("Continuities");
                });
#pragma warning restore 612, 618
        }
    }
}
